### ISSUE TITLE
The implementation of __contains__ in Chap2, C-2.27

### ISSUE THREAD

**Issue by shenxiangzhuang** [jihoonerd/Data_Structures_and_Algorithms_in_Python#1]
Exercise, Chapter 02: OOP, In [14]:
```python
def __contains__(self, item):
    return True if (item - self._start) % 5 == 0 else False
```
I think the number `5` should be replaced by `self._step` :smile:

**Comment by jihoonerd** [comment]
@shenxiangzhuang You are right, I fixed the typo. Thanks for your feedback. :+1:
