### ISSUE TITLE
Range function is not producing same as built in range

### ISSUE THREAD

**Issue by mamikon88** [jihoonerd/Data_Structures_and_Algorithms_in_Python#10]
#  Range                                                              # built in range

r = Range(-1, -7, -2)                                            |  r = range(-1, -7, -2) 
out: [-1, -3, -5, -7]                                               |  out: list(r) [-1, -3, -5]

r = Range(-1, -7, -1)                                           |  r = range(-1, -7, -1)
out: list(r) -> [-1, -2, -3, -4, -5, -6, -7, -8]           |   out: list(r) ->  [-1, -2, -3, -4, -5, -6]

**Comment by jihoonerd** [comment]
@mamikon88 Can you elaborate where and what was the problem you experienced?

**Comment by mamikon88** [comment]
@jihoonerd 
in range function that mimics built in range, in chapter 2 exercise jupiter notebook see [here](https://nbviewer.jupyter.org/github/jihoonerd/Data_Structures_and_Algorithms_in_Python/blob/master/Exercises/Chapter_02.ipynb) 
I compared your implementation with the bult-in function and saw that the output is not the same

**Comment by mamikon88** [comment]
this will affect the exercise question of implementing O(n) complexity function to check `__contains__(var)` (like is a in Range).
`r = range(-1, -7, -2)
a = -7
a in r -> True
`

**Comment by jihoonerd** [comment]
Thanks @mamikon88 , you are right. The `Range` class did not properly handle for the case that parameters are negative numbers. I fixed it through #11 , so let me know if you find something wrong other than the case. :bow:
