### ISSUE TITLE
 missing solutions in chapter 6

### ISSUE THREAD

**Issue by Mainakdey1** [jihoonerd/Data_Structures_and_Algorithms_in_Python#34]
Hey @jihoonerd i noticed that chapter 6 had some missing solutions R 6.8 onwards. Are the solutions of those questions located elsewhere in the repository or do they not exist at all?

(Some of those questions are follow ups on previous questions but some are new as well)

**Comment by jihoonerd** [comment]
Hi @Mainakdey1 . I checked the solutions about Chapter 6. I provided solutions for questions that I was interested in while I was reading the book, so there are many questions left without solutions. I hope I can put more time on other problems later, but it is difficult to say exact time on that.

**Comment by Mainakdey1** [comment]
hey @jihoonerd all good . If it's okay with you, can I put my solutions to those problems as well?
