### ISSUE TITLE
I am wondering why you wrote class Empty(Exception):

### ISSUE THREAD

**Issue by thisisreallife** [jihoonerd/Data_Structures_and_Algorithms_in_Python#6]
https://github.com/jihoonerd/Data_Structures_and_Algorithms_in_Python/blob/ad9011d1bf2159a6963870137f14753aa8db6661/Contents/Chapter07/DoublyLinkedList.py#L4

In the source code author provided in [wiley](http://bcs.wiley.com/he-bcs/Books?action=resource&bcsId=8029&itemId=1118290275&resourceId=31281), I find author did not write this class. Authors used `from ..exceptions import Empty ` but it did not work on my PC(Python 3.6, Win10). Also, there is no fold called __exceptions__ in the source code on wiley.com.  

If I did not get you wrong, the source code provided on wiley.com is incompelete and we must write our own `class Empty(Exception):` to make the code usable? This is the reason you write `class Empty(Exception):` ?

Thanks a lot for providing notebooks and revised pure python code!

**Comment by jihoonerd** [comment]
@thisisreallife First of all,
`from ..exceptions import Empty` means importing `Empty` class from `exception.py`, which is located at its parent directory. It seems Wiley's webpage does not upload the `exceptions.py`, should be placed at the directory, and this will be the reason for the error you face.

Of course, you can work around it by writing `Empty` class in each file, but I would like to suggest writing `exception.py` at the parent directory, and it may solve your problem.

1. Open your editor
2. Write
    ```python
    class Empty(Exception):
        """Error attempting to access an element from an empty container."""
        pass
    ```
3. Save as `exceptions.py`. Be sure to locate it at the same level as `CHXX` folders.
